<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SignInOut</name>
   <tag></tag>
   <elementGuidId>8ffd03de-a727-4219-aa98-bcc20cec958d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>gt-button.hydrated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//gt-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app/ng-component/div/div/div[2]/div/ghr-home/div[2]/div/gt-home-dashboard/div/div[2]/gt-component-loader/gt-attendance-info/div/div/div[3]/gt-button[1][count(. | //*[@shade = 'primary']) = count(//*[@shade = 'primary'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-button</value>
      <webElementGuid>8643a5b3-6478-4011-a6f9-66be589659c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>ab3d5513-9a31-4e88-913b-b0fe778b9d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>1e1748a2-24d6-4864-b7d0-5ebe147ae873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app/ng-component/div/div/div[2]/div/ghr-home/div[2]/div/gt-home-dashboard/div/div[2]/gt-component-loader/gt-attendance-info/div/div/div[3]/gt-button[1]</value>
      <webElementGuid>a53e8e36-21c6-4f3e-9f11-64ef70d56b39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-button</value>
      <webElementGuid>5df4617c-b394-4dfc-8973-a37f8fc0275e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
