<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SignInOut</name>
   <tag></tag>
   <elementGuidId>8ffd03de-a727-4219-aa98-bcc20cec958d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//gt-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>gt-button.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-button</value>
      <webElementGuid>d510bf42-6d7f-47b7-b7c0-715ddf9d708f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>5641ff7d-7cae-4c9e-93fd-e900d1b71634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>0fbb13c7-e5da-47fc-9b91-d93f292027f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mobile-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;gt-home-dashboard mb-1.5x&quot;]/div[@class=&quot;gt-widget-wrapper bg-white rounded-m border-secondary-200 hover:shadow-lg ng-star-inserted&quot;]/gt-component-loader[1]/gt-attendance-info[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-1.5x h-18x widget-border bg-primary-50&quot;]/div[1]/div[@class=&quot;btn-container mt-3x flex flex-row-reverse justify-between ng-star-inserted&quot;]/gt-button[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>4e6b5393-f033-4a51-90b2-9f0aac47899d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-button</value>
      <webElementGuid>dcdc4f7d-019a-4f1a-90e5-0b5a370818c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
