<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-button_Review_hydrated</name>
   <tag></tag>
   <elementGuidId>5d95f72c-8301-4e18-91e1-0e64510382b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//gt-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>gt-button.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-button</value>
      <webElementGuid>ab48d831-7559-4bda-862d-ec63c0c06fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>e2818285-2914-4ff2-94d5-fdcd3d468acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>cb824ecf-e878-4ba7-a3a4-19d9b1e5eedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;gt-home-dashboard mb-1.5x&quot;]/div[@class=&quot;gt-widget-wrapper bg-white rounded-m border-secondary-200 hover:shadow-lg ng-star-inserted&quot;]/gt-component-loader[1]/gt-attendance-info[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;p-1.5x h-18x widget-border bg-primary-50&quot;]/div[1]/div[@class=&quot;btn-container mt-3x flex flex-row-reverse justify-between ng-star-inserted&quot;]/gt-button[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>172d26d2-71cb-4f2e-9f99-67b6f800caeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-button</value>
      <webElementGuid>27836cd7-5ba1-4d8a-938f-8d8cbb972007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
