<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-button_Tell us your work location_flex j_ae71c3</name>
   <tag></tag>
   <elementGuidId>bba201dc-dff2-4d8b-8404-fe6a4f74dff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/gt-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>gt-button.flex.justify-end.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-button</value>
      <webElementGuid>86581d36-ec5b-4b4d-9410-7381baf0a3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>37ecff42-fb5d-4e5f-a6f7-656d98d03df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end hydrated</value>
      <webElementGuid>a9ec372b-d30a-445b-b352-03dd18f15e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/gt-popup-modal[@class=&quot;hydrated&quot;]/div[@class=&quot;body-content&quot;]/div[@class=&quot;flex justify-between&quot;]/div[@class=&quot;col-md-4 col-lg-4 attendance-info mb-2x&quot;]/gt-button[@class=&quot;flex justify-end hydrated&quot;]</value>
      <webElementGuid>4f8270ff-28c2-4348-8e75-ac68b75d0ce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/gt-button</value>
      <webElementGuid>8f6af6c8-e12e-4a70-890c-aa5e9028594c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
