<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-dropdown_Tell us your work location_hydrated</name>
   <tag></tag>
   <elementGuidId>7bf39a33-46a4-4442-bc85-9a4c37f3d311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//gt-dropdown</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>gt-dropdown.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-dropdown</value>
      <webElementGuid>6ec4646a-e90d-4534-9794-cf1816997f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>be9b397b-5b96-427a-a5a9-fb8a0907e246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mandatory</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c152cc1-81ab-4aef-b94f-ef7b2e42f499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hydrated</value>
      <webElementGuid>820ed499-31a4-4fb6-b72f-9a321dfde31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/gt-popup-modal[@class=&quot;hydrated&quot;]/div[@class=&quot;body-content&quot;]/div[@class=&quot;flex justify-between&quot;]/div[@class=&quot;flex flex-col flex-1 attendance-info&quot;]/div[@class=&quot;mb-3.5x ng-star-inserted&quot;]/gt-dropdown[@class=&quot;hydrated&quot;]</value>
      <webElementGuid>df32f2c3-9b56-4996-820e-5756ec09b404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gt-dropdown</value>
      <webElementGuid>46f68b85-ab67-4072-a4a1-d3be2a1df8b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
