<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In-ydrated-af9</name>
   <tag></tag>
   <elementGuidId>8976fe51-8bbe-4d20-a8d6-425590bc4177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;primary&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02f93ef6-1d2f-46bb-961e-650686c036f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-medium</value>
      <webElementGuid>41b9c9db-eafa-49a0-ba02-8f43c0df6ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>744b72f2-2fa2-4c65-b01b-77ba3bd263d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>46c9ffcd-f9cc-4f6d-8b71-a5db0d4c52ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>80353daf-ee54-4cbc-9014-334b867839f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;btn btn-primary btn-medium&quot;]</value>
      <webElementGuid>ca91d11d-2515-4f84-bec6-3b466ed48b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TempSignin/Page_greytHR/gt-button_Review_hydrated</value>
      <webElementGuid>4a7d9828-a1f8-4528-a70c-39137c76de44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98b9c29e-921a-41cb-900d-4ee378f5da40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>0ef30083-5bcc-4dc3-ba5c-b69fede17204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'primary' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>17e3463c-c7d5-446d-9bb1-a3c3c8bd40c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
