<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gt-button_Tell us your work location_flex j_ae71c3</name>
   <tag></tag>
   <elementGuidId>d85a4f14-aee5-40a9-b38f-6f583e3d1e82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/gt-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>gt-button.flex.justify-end.hydrated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>gt-button</value>
      <webElementGuid>5ff88aa5-342b-4a64-aec2-c6fe2d545434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shade</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>0353e430-12c1-4689-94cc-8fef871da1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end hydrated</value>
      <webElementGuid>7eb2981b-f761-466e-ae61-9aad89b74e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[@class=&quot;ng-tns-0-1&quot;]/app[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;desktop-view&quot;]/div[@class=&quot;side-and-content&quot;]/div[@class=&quot;container-fluid app-container px-0&quot;]/div[@class=&quot;router-container pb-15 container-fluid&quot;]/ghr-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page page-home ng-star-inserted&quot;]/div[@class=&quot;home-dashboard&quot;]/gt-home-dashboard[@class=&quot;ng-star-inserted&quot;]/gt-popup-modal[@class=&quot;hydrated&quot;]/div[@class=&quot;body-content&quot;]/div[@class=&quot;flex justify-between&quot;]/div[@class=&quot;col-md-4 col-lg-4 attendance-info mb-2x&quot;]/gt-button[@class=&quot;flex justify-end hydrated&quot;]</value>
      <webElementGuid>d1807579-d3e5-49bc-be79-63856a270671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/gt-button</value>
      <webElementGuid>693bde96-b620-4589-ad08-dd833de176f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
